---
kind: pipeline
name: default

steps:
- name: build-ansible  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo:
      from_secret: docker_repo
    auto_tag: true
    dockerfile: ./Dockerfile
